language: ruby

sudo: false

rvm:
  - 2.2.4
  - 2.3.0
  - 2.3.3
  - 2.4.0

gemfile:
  - Gemfile

notifications:
  email:
    - jacob.hammack@hammackj.com
  irc: "irc.freenode.org#risu"

before_install:
  - gem --version
